# fly.toml app configuration file generated for tborg-status on 2024-02-16T09:11:45-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tborg-status"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
